ID_Item_Table = {
    "Pot.img": 'sources/Item/Pot/tools. (2).png',
    "Pot.des": 'sources/Item/Pot/Description.txt',
    "Hoe.des": 'sources/Item/Hoe/Description.txt',
    "Hoe.img": 'sources/Item/Hoe/tools..png',
    "Axe.img": 'sources/Item/Axe/Axe.png',
    "Axe.des": 'sources/Item/Axe/Description.txt',
    "Seed_tomato.img": 'sources/Item/Seed_tomato/crops. (2)_169.png',
    'Seed_tomato.des': 'sources/Item/Seed_tomato/Description.txt',
    "Seed_corn.img": 'sources/Item/Seed_corn/crops. (2)_121.png',
    'Seed_corn.des': 'sources/Item/Seed_corn/Description.txt',
    "Seed_03.img": 'sources/Item/Seed_03/crops. (2)_193.png',
    'Seed_03.des': 'sources/Item/Seed_03/Description.txt',
    'Seed_fruittree.img': 'sources/Item/Seed_fruittree/fruitTrees__001.png',
    'Seed_fruittree.des': 'sources/Item/Seed_fruittree/Description.txt',
    "Wood.img": 'sources/Item/Wood/wood.png',
    "Wood.des": 'sources/Item/Wood/Description.txt',
    "Fruit_tomato.img": 'sources/Item/Fruit_tomato/Crop_Spritesheet_097.png',
    "Fruit_tomato.des": 'sources/Item/Fruit_tomato/Description.txt',
    "Fruit_fruittree.img": 'sources/Item/Fruit_fruittree/Crop_Spritesheet_043.png',
    "Fruit_fruittree.des": 'sources/Item/Fruit_fruittree/Description.txt',
    "Fruit_corn.img": 'sources/Item/Fruit_corn/Crop_Spritesheet_109.png',
    "Fruit_corn.des": 'sources/Item/Fruit_corn/Description.txt'

}
